services:
  docker-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888:18888"
    expose:
      - "18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "edict.apphost-e50c6c8888-postgres-data"
        read_only: false
    networks:
      - "aspire"
  migration:
    image: "${MIGRATION_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__postgresdb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=postgresdb"
      DOTNET_ENVIRONMENT: "Production"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "migration"
    depends_on:
      postgres:
        condition: "service_started"
    networks:
      - "aspire"
  elasticsearch:
    image: "docker.io/library/elasticsearch:8.17.3"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
    expose:
      - "9200"
      - "9300"
    volumes:
      - type: "volume"
        target: "/usr/share/elasticsearch/data"
        source: "edict.apphost-e50c6c8888-elasticsearch-data"
        read_only: false
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      ConnectionStrings__postgresdb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=postgresdb"
      ConnectionStrings__elasticsearch: "http://elastic:${ELASTICSEARCH_PASSWORD}@elasticsearch:9200"
      ASPNETCORE_ENVIRONMENT: "Production"
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    expose:
      - "${API_PORT}"
    depends_on:
      postgres:
        condition: "service_started"
      migration:
        condition: "service_completed_successfully"
      elasticsearch:
        condition: "service_started"
    networks:
      - "aspire"
  app:
    image: "${APP_IMAGE}"
    environment:
      NODE_ENV: "production"
      services__api__http__0: "http://api:${API_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "app"
    expose:
      - "3000"
    depends_on:
      api:
        condition: "service_started"
    networks:
      - "aspire"
  gateway:
    image: "mcr.microsoft.com/dotnet/nightly/yarp:2.3.0-preview.4"
    command:
      - "/app/yarp.dll"
    entrypoint:
      - "dotnet"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      services__api__http__0: "http://api:${API_PORT}"
      REVERSEPROXY__ROUTES__route0__MATCH__PATH: "/api/{**catch-all}"
      REVERSEPROXY__ROUTES__route0__CLUSTERID: "cluster_api"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__0__PathRemovePrefix: "/api"
      REVERSEPROXY__ROUTES__route1__MATCH__PATH: "/{**catch-all}"
      REVERSEPROXY__ROUTES__route1__CLUSTERID: "cluster_app"
      REVERSEPROXY__CLUSTERS__cluster_api__DESTINATIONS__destination1__ADDRESS: "https+http://api"
      REVERSEPROXY__CLUSTERS__cluster_app__DESTINATIONS__destination1__ADDRESS: "http://app"
      services__app__http__0: "http://app:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "gateway"
    ports:
      - "5000:5000"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  edict.apphost-e50c6c8888-postgres-data:
    driver: "local"
  edict.apphost-e50c6c8888-elasticsearch-data:
    driver: "local"
