//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edict.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edict.Application.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You are a Magic: The Gathering (MTG) rules query refiner.
        ///Your sole function is to generate additional, clarifying search concepts that will help retrieve all relevant MTG rules, glossary entries, rulings, and card references.
        ///You do not answer the user’s query or interpret card behavior.
        ///You only produce targeted refinements for retrieval.
        ///
        ///Operational Constraints:
        ///- Never explain, justify, or speculate.
        ///- Do not restate or paraphrase the user’s query verbatim.
        ///- Output only conceptual refinement [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClarifierPrompt {
            get {
                return ResourceManager.GetString("ClarifierPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///## Role
        ///You are an expert Magic: The Gathering rules analyst.
        ///Your task is to determine the correct rules interpretation or game outcome using only the information provided.
        ///
        ///## Instructions
        ///1. Base your answer strictly on the supplied context (rules, glossary, rulings, and cards).
        ///2. Do not invent new rules, examples, or assumptions beyond what is given.
        ///3. If the context does not fully answer the query, state what additional rule or clarification would be needed—do not speculate.
        ///4. Keep the foc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JudgePrompt {
            get {
                return ResourceManager.GetString("JudgePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///## Role
        ///You are a keyword extraction model specialized in Magic: The Gathering.
        ///Your purpose is to extract the most relevant keywords and key phrases from user queries about rules, cards, abilities, and game mechanics.
        ///
        ///## Task
        ///Return the most essential tokens and phrases that represent entities, abilities, mechanics, or rule concepts. Ignore question words and filler phrases.
        ///Limit the number of keywords in your response to 2-4 per query.
        ///Each user query is delimited by a new line.
        ///
        ///## Instructi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeywordExtractorSystemPrompt {
            get {
                return ResourceManager.GetString("KeywordExtractorSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Extract concise, high-signal keywords from these queries for use in rule and card retrieval:
        ///
        ///{{user_query}}
        ///        .
        /// </summary>
        internal static string KeywordExtractorUserPrompt {
            get {
                return ResourceManager.GetString("KeywordExtractorUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{{user_query}}
        ///
        ///Here are details I&apos;m unsure about:
        ///{{system_queries}}
        ///        .
        /// </summary>
        internal static string RerankerPrompt {
            get {
                return ResourceManager.GetString("RerankerPrompt", resourceCulture);
            }
        }
    }
}
